/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.LocalDeEstoqueDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import model.LocalDeEstoque;
import model.LocalDeEstoqueTableModel;

/**
 *
 * @author guilherme.oliveira
 */
public class UIBuscarEstoque extends javax.swing.JDialog {

    private LocalDeEstoqueDAO estoqueDAO;
    private UICadMovimento uiCadMovimento;
    private LocalDeEstoqueTableModel estoqueTableModel;
    private TableRowSorter<LocalDeEstoqueTableModel> sorter;
    private boolean isEstoqueOrigem;

    public UIBuscarEstoque() {
    }

    public UIBuscarEstoque(UICadMovimento uiCadMovimento, boolean isEstoqueOrigem) {
        initComponents();
        this.uiCadMovimento = uiCadMovimento;
        estoqueDAO = new LocalDeEstoqueDAO();
        estoqueTableModel = new LocalDeEstoqueTableModel();
        sorter = new TableRowSorter<>(estoqueTableModel);
        jtEstoques.setRowSorter(sorter);
        this.isEstoqueOrigem = isEstoqueOrigem;
        jtEstoques.setModel(estoqueTableModel);
        buscar();
        configurarTabela();
    }

    private void configurarTabela() {
        jtEstoques.getTableHeader().setResizingAllowed(false);
        jtEstoques.setAutoResizeMode(jtEstoques.AUTO_RESIZE_OFF);
        jtEstoques.getColumnModel().getColumn(0).setPreferredWidth(322);
        jtEstoques.getColumnModel().getColumn(1).setPreferredWidth(50);
    }

    private void buscar() {
        Menu.carregamento(true);
        new Thread(() -> {
            try {
                ArrayList<LocalDeEstoque> estoques = estoqueDAO.buscar();

                for (LocalDeEstoque estoque : estoques) {
                    estoqueTableModel.addRow(estoque);
                }

            } catch (Exception ex) {
                Logger.getLogger(UIBuscarEstoque.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage(),
                        "Erro ao buscar locais de estoques", JOptionPane.ERROR_MESSAGE);
            }
            Menu.carregamento(false);
        }).start();
    }

    private void pesquisar() {
        String nome = jtfNome.getText().trim();
        boolean ativos = jchAtivos.isSelected();

        List<RowFilter<Object, Object>> filters = new ArrayList<>();
        filters.add(RowFilter.regexFilter("(?i)" + nome, 0));
        filters.add(RowFilter.regexFilter("(?i)" + ativos, 1));

        sorter.setRowFilter(RowFilter.andFilter(filters));
    }

    private void carregarCampoEstoqueOrigem() {
        try {
            LocalDeEstoque estoqueOrigem = pegarEstoqueSelecionado();
            if (estoqueOrigem != null) {
                uiCadMovimento.setEstoqueOrigem(estoqueOrigem);
                this.uiCadMovimento.getJtfEstoqueOrigem().setText(estoqueOrigem.getNome());

                if (!this.uiCadMovimento.getJtfEstoqueDestino().getText().isEmpty()) {

                    this.uiCadMovimento.getJbAdicionarProduto().setEnabled(true);
                    this.uiCadMovimento.getJbAddPatrimonio().setEnabled(true);
                }
                this.dispose();
            }
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void carregarCampoEstoqueDestino() {
        try {
            LocalDeEstoque estoqueDestino = pegarEstoqueSelecionado();
            if (estoqueDestino != null) {
                uiCadMovimento.setEstoqueDestino(estoqueDestino);
                this.uiCadMovimento.getJtfEstoqueDestino().setText(estoqueDestino.getNome());

                this.dispose();
            }
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private LocalDeEstoque pegarEstoqueSelecionado() throws IndexOutOfBoundsException {
        try {
            int linhaSelecionada = jtEstoques.getRowSorter().convertRowIndexToModel(jtEstoques.getSelectedRow());
            return estoqueTableModel.getRowValue(linhaSelecionada);
        } catch (IndexOutOfBoundsException e) {
            throw new ArrayIndexOutOfBoundsException("Selecione o estoque!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtEstoques = new javax.swing.JTable();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jbCarregar = new javax.swing.JButton();
        jchAtivos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Estoque");
        setModal(true);
        setResizable(false);

        jtEstoques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtEstoques);

        jlNome.setText("Nome");

        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbCarregar.setText("Carregar");
        jbCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarregarActionPerformed(evt);
            }
        });

        jchAtivos.setText("Inativos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchAtivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCarregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar)
                    .addComponent(jbCarregar)
                    .addComponent(jchAtivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        pesquisar();
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jbCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarregarActionPerformed
        if (isEstoqueOrigem) {
            carregarCampoEstoqueOrigem();
        } else {
            carregarCampoEstoqueDestino();
        }
    }//GEN-LAST:event_jbCarregarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_jbPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIBuscarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIBuscarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIBuscarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIBuscarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIBuscarEstoque dialog = new UIBuscarEstoque();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCarregar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JCheckBox jchAtivos;
    private javax.swing.JLabel jlNome;
    private javax.swing.JTable jtEstoques;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
