/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import model.Funcionario;
import model.FuncionariosTableModel;
import services.FuncionarioServicos;
import services.ServicosFactory;

/**
 *
 * @author guilherme.oliveira
 */
public class UIBuscarFuncionariosPJ extends javax.swing.JDialog {

    private UICadFeriasFuncionarioPJ uiCadFerias;
    private FuncionarioServicos fs;
    private FuncionariosTableModel funcionariosPJTableModel;
    private TableRowSorter<FuncionariosTableModel> sorter;

    public UIBuscarFuncionariosPJ() {}

    public UIBuscarFuncionariosPJ(UICadFeriasFuncionarioPJ uiCadFerias) {
        initComponents();
        this.uiCadFerias = uiCadFerias;
        this.fs = ServicosFactory.getFUNCIONARIOSERVICOS();
        funcionariosPJTableModel = new FuncionariosTableModel();
        sorter = new TableRowSorter<>(funcionariosPJTableModel);
        jtFuncionariosPJ.setRowSorter(sorter);
        buscar();
        pesquisar();
        configurarTabela();
    }

    private void configurarTabela() {
        jtFuncionariosPJ.getTableHeader().setResizingAllowed(false);
        jtFuncionariosPJ.setAutoResizeMode(jtFuncionariosPJ.AUTO_RESIZE_OFF);
        jtFuncionariosPJ.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtFuncionariosPJ.getColumnModel().getColumn(1).setPreferredWidth(464);
        jtFuncionariosPJ.getColumnModel().getColumn(2).setPreferredWidth(50);
    }//configurarTabela

    private void buscar() {
        try {

            ArrayList<Funcionario> funcionarios = fs.buscarFuncionariosPJ();

            for (Funcionario funcionario : funcionarios) {
                funcionariosPJTableModel.addRow(funcionario);
            }

            jtFuncionariosPJ.setModel(funcionariosPJTableModel);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    e.getMessage(),
                    "Erro ao buscar funcionários PJ",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//buscar

    private void pesquisar() {
        String nome = jtfNome.getText().trim();
        boolean ativos = jchAtivos.isSelected();
        
        List<RowFilter<Object, Object>> filters = new ArrayList<>();
        filters.add(RowFilter.regexFilter("(?i)" + nome, 1));
        filters.add(RowFilter.regexFilter("(?i)" + ativos, 2));
        
        sorter.setRowFilter(RowFilter.andFilter(filters));
    }

    private void carregarCamposNaTelaDeCadastro() {
        Funcionario funcionario = pegarFuncionarioSelecionado();
        if (funcionario != null) {
            uiCadFerias.setFuncionario(funcionario);
            this.uiCadFerias.getJtfChapa().setText(funcionario.getChapa());
            this.uiCadFerias.getJtfNome().setText(funcionario.getNome());
            this.dispose();
        }
    }

    private Funcionario pegarFuncionarioSelecionado() {
        int linhaSelecionada = jtFuncionariosPJ.getRowSorter().convertRowIndexToModel(jtFuncionariosPJ.getSelectedRow());
        return funcionariosPJTableModel.getRowValue(linhaSelecionada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtFuncionariosPJ = new javax.swing.JTable();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jbCarregar = new javax.swing.JButton();
        jchAtivos = new javax.swing.JCheckBox();
        jbPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Colaborador");
        setModal(true);
        setResizable(false);

        jtFuncionariosPJ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtFuncionariosPJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFuncionariosPJMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFuncionariosPJ);

        jlNome.setText("Nome");

        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
        });

        jbCarregar.setText("Carregar");
        jbCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarregarActionPerformed(evt);
            }
        });

        jchAtivos.setSelected(true);
        jchAtivos.setText("Ativos");
        jchAtivos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jchAtivosItemStateChanged(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jchAtivos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbPesquisar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCarregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarregar)
                    .addComponent(jchAtivos)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        pesquisar();
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jbCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarregarActionPerformed
        carregarCamposNaTelaDeCadastro();
    }//GEN-LAST:event_jbCarregarActionPerformed

    private void jtFuncionariosPJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFuncionariosPJMouseClicked
        if (evt.getClickCount() == 2) {
            carregarCamposNaTelaDeCadastro();
        }
    }//GEN-LAST:event_jtFuncionariosPJMouseClicked

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jchAtivosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jchAtivosItemStateChanged
        pesquisar();
    }//GEN-LAST:event_jchAtivosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIBuscarFuncionariosPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIBuscarFuncionariosPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIBuscarFuncionariosPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIBuscarFuncionariosPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIBuscarFuncionariosPJ dialog = new UIBuscarFuncionariosPJ();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCarregar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JCheckBox jchAtivos;
    private javax.swing.JLabel jlNome;
    private javax.swing.JTable jtFuncionariosPJ;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
