/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.os.PessoaDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import model.os.Pessoa;
import model.os.PessoaTableModel;

/**
 *
 * @author guilherme.oliveira
 */
public class UIBuscarResponsavel extends javax.swing.JDialog {

    private PessoaDAO pessoaDAO;
    private UICadMovimento uiCadMovimento;
    private PessoaTableModel pessoaTableModel;
    private TableRowSorter<PessoaTableModel> sorter;

    public UIBuscarResponsavel() {
    }

    public UIBuscarResponsavel(UICadMovimento uiCadMovimento) {
        initComponents();
        this.uiCadMovimento = uiCadMovimento;
        pessoaDAO = new PessoaDAO();
        pessoaTableModel = new PessoaTableModel();
        sorter = new TableRowSorter<>(pessoaTableModel);
        jtPessoas.setRowSorter(sorter);
        buscar();
        configurarTabela();
    }

    private void configurarTabela() {
        jtPessoas.getTableHeader().setResizingAllowed(false);
        jtPessoas.setAutoResizeMode(jtPessoas.AUTO_RESIZE_OFF);
        jtPessoas.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtPessoas.getColumnModel().getColumn(1).setPreferredWidth(282);
        jtPessoas.getColumnModel().getColumn(2).setPreferredWidth(50);
    }
    
    private void buscar() {
        try {
            ArrayList<Pessoa> pessoas = pessoaDAO.buscar();

            for (Pessoa pessoa : pessoas) {
                pessoaTableModel.addRow(pessoa);
            }

            jtPessoas.setModel(pessoaTableModel);

        } catch (Exception e) {
            Logger.getLogger(UIBuscarResponsavel.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null,
                    e.getMessage(),
                    "Erro ao buscar responsavel",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void pesquisar() {
        String nome = jtfNome.getText().trim();
        boolean ativos = jchAtivos.isSelected();

        List<RowFilter<Object, Object>> filters = new ArrayList<>();
        filters.add(RowFilter.regexFilter("(?i)" + nome, 1));
        filters.add(RowFilter.regexFilter("(?i)" + ativos, 2));

        sorter.setRowFilter(RowFilter.andFilter(filters));
    }

    private Pessoa pegarPessoaSelecionado() throws IndexOutOfBoundsException {
        try {
            int linhaSelecionada = jtPessoas.getRowSorter().convertRowIndexToModel(jtPessoas.getSelectedRow());

            return pessoaTableModel.getRowValue(linhaSelecionada);

        } catch (IndexOutOfBoundsException e) {
            throw new IndexOutOfBoundsException("Selecione a pessoa!");
        }

    }

    private void carregarCamposNaTelaDeCadastro() {
        try {
            Pessoa pessoa = pegarPessoaSelecionado();
            if (pessoa != null) {
                uiCadMovimento.setResponsavel(pessoa);
                this.uiCadMovimento.getJtfResponsavel().setText(pessoa.getNome());
                this.dispose();
            }
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jbCarregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPessoas = new javax.swing.JTable();
        jchAtivos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Responsável");
        setModal(true);
        setResizable(false);

        jlNome.setText("Nome");

        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeKeyReleased(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbCarregar.setText("Carregar");
        jbCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarregarActionPerformed(evt);
            }
        });

        jtPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPessoas);

        jchAtivos.setSelected(true);
        jchAtivos.setText("Ativos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchAtivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCarregar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar)
                    .addComponent(jbCarregar)
                    .addComponent(jchAtivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarregarActionPerformed
        carregarCamposNaTelaDeCadastro();
    }//GEN-LAST:event_jbCarregarActionPerformed

    private void jtfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyReleased
        pesquisar();
    }//GEN-LAST:event_jtfNomeKeyReleased

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_jbPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIBuscarResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIBuscarResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIBuscarResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIBuscarResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIBuscarResponsavel dialog = new UIBuscarResponsavel();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCarregar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JCheckBox jchAtivos;
    private javax.swing.JLabel jlNome;
    private javax.swing.JTable jtPessoas;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
