/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author guilherme.oliveira
 */
public class UIC extends javax.swing.JInternalFrame {

    private UIFuncionario parent;

    /**
     * Creates new form UIC
     *
     * @param parent
     */
    public UIC(UIFuncionario parent) {
        this.parent = parent;
        initComponents();
    }

    public UIFuncionario getUiFuncionario() {
        return parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCCa = new javax.swing.JLabel();
        jtfCCA = new javax.swing.JTextField();

        setClosable(true);
        setTitle("CA");

        jlCCa.setText("Digite o CA do EPI");

        jtfCCA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCCAKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jlCCa)
                .addGap(18, 18, 18)
                .addComponent(jtfCCA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCCa)
                    .addComponent(jtfCCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCCAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCCAKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!jtfCCA.getText().isEmpty()) {
                parent.setCa(jtfCCA.getText());
                if (parent.getCodFichaEpi() == 0) {
                    UIEntregar uiEntregar = new UIEntregar(this);
                    Menu menu = parent.getUiControleEpi().getMenu();
                    uiEntregar.setLocation(
                            menu.getJdpAreaTrabalho().getWidth() / 2 - uiEntregar.getWidth() / 2,
                            menu.getJdpAreaTrabalho().getHeight() / 2 - uiEntregar.getHeight() / 2);
                    menu.getJdpAreaTrabalho().add(uiEntregar);
                    uiEntregar.setVisible(true);
                    this.dispose();
                } else {
                    parent.inserirHistorico();
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Campo CA obrigatório!");
            }
        }
    }//GEN-LAST:event_jtfCCAKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCCa;
    private javax.swing.JTextField jtfCCA;
    // End of variables declaration//GEN-END:variables
}
