/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import cis.sdk.CisBiox;
import dao.DAOFactory;
import dao.FichaEpiDAO;
import exceptions.RetornosException;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Funcionario;

/**
 *
 * @author guilherme.oliveira
 */
public class UIDevolver extends javax.swing.JInternalFrame {

    private static byte[] digital;
    private UIFuncionario parent;
    private static int senha = 1;

    /**
     * Creates new form UIDevolver
     */
    public UIDevolver(UIFuncionario parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSenha = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jlOk = new javax.swing.JLabel();
        jbLerDigital = new javax.swing.JButton();
        jbDigitarSenha = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Devolver");

        jlSenha.setText("Senha");

        jpfSenha.setEnabled(false);
        jpfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfSenhaKeyPressed(evt);
            }
        });

        jlOk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlOk.setForeground(new java.awt.Color(51, 102, 255));
        jlOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jbLerDigital.setText("Ler Digital");
        jbLerDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLerDigitalActionPerformed(evt);
            }
        });

        jbDigitarSenha.setText("Digitar Senha");
        jbDigitarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDigitarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlOk, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jlSenha)
                            .addComponent(jpfSenha))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbLerDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jbDigitarSenha)
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlOk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLerDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDigitarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String strSenha = new String(jpfSenha.getPassword());
                senha = Integer.parseInt(strSenha);
                Funcionario f = parent.getFuncionario();
                if (senha == f.getSenha()) {
                    parent.cadastrarFichaEpi();
                    parent.inserirHistorico();
                    parent.getEfTableModel().clear();
                    parent.preencherTabelaEpiFuncionario();
                    parent.gethTableModel().clearTable();
                    parent.preencherHistorico();
                    this.dispose();
                } else {
                    jpfSenha.setText("");
                    jpfSenha.requestFocus();
                    JOptionPane.showMessageDialog(null, "Senha incorreta!", "Aviso", JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception nfe) {
                JOptionPane.showMessageDialog(null, "" + nfe.getMessage());
            }
        }
    }//GEN-LAST:event_jpfSenhaKeyPressed

    private void jbLerDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLerDigitalActionPerformed
        lerDigital();
    }//GEN-LAST:event_jbLerDigitalActionPerformed

    private void jbDigitarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDigitarSenhaActionPerformed
        Funcionario f = parent.getFuncionario();
        if (f.getSenha() != 0) {
            jpfSenha.setEnabled(true);
            jpfSenha.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Senha não cadastrada!",
                    "Erro ao autenticar senha!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbDigitarSenhaActionPerformed

    /**
     * Método usado para ler digital do funcionário
     */
    public void lerDigital() {
        Funcionario f = parent.getFuncionario();
        //testa se funcionario tem alguma digital cadatrada
        if (f.getFinger1() != null || f.getFinger2() != null || f.getFinger3() != null
                || f.getFinger4() != null || f.getFinger5() != null || f.getFinger6() != null) {
            CisBiox biox = new CisBiox();
            try {

                int iRetorno = biox.iniciar();
                
                if (iRetorno != 1) {
                    throw new RetornosException(iRetorno);
                }

                digital = biox.capturarDigital();

                if (biox.getResultado() != 1) {
                    biox.finalizar();
                    jlOk.setText(biox.mensagens(biox.getResultado()));
                    jlOk.setForeground(Color.red);
                }

                iRetorno = biox.finalizar();

                if (iRetorno != 1) {
                    jlOk.setText(biox.mensagens(iRetorno));
                    jlOk.setForeground(Color.red);
                    return;
                }

                iRetorno = biox.iniciar();

                if (iRetorno != 1) {
                    throw new RetornosException(iRetorno);
                }

                byte[][] digitais = new byte[6][699];
                digitais[0] = f.getFinger1();
                digitais[1] = f.getFinger2();
                digitais[2] = f.getFinger3();
                digitais[3] = f.getFinger4();
                digitais[4] = f.getFinger5();
                digitais[5] = f.getFinger6();

                for (int i = 0; i < digitais.length; i++) {
                    iRetorno = biox.compararDigital(digital, digitais[i]);
                    if (iRetorno == 1) {
                        break;
                    }
                }//fecha for
                switch (iRetorno) {
                    case 1:
                        FichaEpiDAO dao = DAOFactory.getFICHAEPIDAO();
                        parent.setCodFichaEpi(dao.cadastrarFicha());
                        parent.inserirHistorico();
                        this.dispose();
                        break;
                    case -2:
                        jlOk.setText("Digital não encontrada!");
                        jlOk.setForeground(Color.red);
                        break;
                    default:
                        jlOk.setText(biox.mensagens(iRetorno));
                        jlOk.setForeground(Color.red);
                        break;
                }
                biox.finalizar();
            } catch (NullPointerException ne) {
                biox.finalizar();
                jlOk.setText("Erro ao ler digital! ");
                jlOk.setForeground(Color.red);
            } catch (RetornosException re) {
                biox.finalizar();
                jlOk.setText("Erro ao ler digital! " + re.getMessage());
                jlOk.setForeground(Color.red);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), 
                        "Erro ao ler digital", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma digital cadastrada!",
                    "Erro ao ler digital", JOptionPane.ERROR_MESSAGE);
        }
    }//fecha lerDigital

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jbDigitarSenha;
    private javax.swing.JButton jbLerDigital;
    private javax.swing.JLabel jlOk;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JPasswordField jpfSenha;
    // End of variables declaration//GEN-END:variables
}
