/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ponto;

import dao.DAOFactory;
import dao.ponto.RelogioPontoDAO;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ponto.RelogioPonto;
import model.ponto.RelogioPontoTableModel;
import services.RelogioPontoServicos;
import services.ServicosFactory;
import view.Menu;

/**
 *
 * @author guilherme.oliveira
 */
public class UIManRelogioPonto extends javax.swing.JDialog {

    private RelogioPontoTableModel relogiosTableModel = new RelogioPontoTableModel();
    private boolean cadastrando;
    private RelogioPontoServicos rps;

    /**
     * Creates new form UIManRelogioPonto
     */
    public UIManRelogioPonto() {
        this.rps = ServicosFactory.getRELOGIOPONTOSERVICOS();
        initComponents();
        buscarRelogios();
    }

    public boolean isCadastrando() {
        return cadastrando;
    }

    public void setCadastrando(boolean cadastrando) {
        this.cadastrando = cadastrando;
    }

    public RelogioPontoTableModel getRelogiosTableModel() {
        return relogiosTableModel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtRelogios = new javax.swing.JTable();
        jbNovo = new javax.swing.JButton();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jchAtivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manutenção de Relógios Ponto");
        setModal(true);
        setResizable(false);

        jtRelogios.setModel(new RelogioPontoTableModel());
        jtRelogios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtRelogiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtRelogios);

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jlNome.setText("Nome");

        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jchAtivo.setSelected(true);
        jchAtivo.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jbPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNovo)
                    .addComponent(jbPesquisar)
                    .addComponent(jbEditar)
                    .addComponent(jchAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        cadastrando = true;
        UICadRelogioPonto telaCadREP = new UICadRelogioPonto(null, this);
        if (!telaCadREP.isVisible()) {
            telaCadREP.setVisible(true);
        }
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        buscarRelogios();
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarRelogios();
        }
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jtRelogiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtRelogiosMouseClicked
        if (evt.getClickCount() == 2) {
            cadastrando = false;
            abrirTelaCadRelogioPonto();
        }
    }//GEN-LAST:event_jtRelogiosMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        if (getRelogioPontoSelecionado() != null) {
            cadastrando = false;
            abrirTelaCadRelogioPonto();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o relógio para edição", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    /**
     * abre tela de cadastro de relogios ponto
     */
    private void abrirTelaCadRelogioPonto() {
        UICadRelogioPonto telaCadREP = new UICadRelogioPonto(getRelogioPontoSelecionado(), this);
        if (!telaCadREP.isVisible()) {
            telaCadREP.setVisible(true);
        }
    }//abrirTelaCadRelogioPonto

    /**
     * Método usado para buscar/filtrar relógios ponto cadastrados
     */
    public void buscarRelogios() {
        Menu.jpbBarraProgresso.setIndeterminate(true);
        Menu.jpbBarraProgresso.setVisible(true);

        new Thread() {
            @Override
            public void run() {
                try {
                    relogiosTableModel.clear();
                    
                    String query = "";
                    if (!jtfNome.getText().isEmpty()) {
                        query += " and NOME LIKE '%" + jtfNome.getText() + "%'";
                    }

                    query += " and ATIVO = " + jchAtivo.isSelected();

                    ArrayList<RelogioPonto> relogios = rps.buscar(query);

                    for (RelogioPonto relogio : relogios) {
                        relogiosTableModel.addRow(relogio);
                    }//for

                    jtRelogios.setModel(relogiosTableModel);

                    if (relogios.isEmpty()) {
                        JOptionPane.showMessageDialog(UIManRelogioPonto.this, "Nenhum registro encontrado");
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(),
                            "Erro ao buscar relógios ponto",
                            JOptionPane.ERROR_MESSAGE);
                } finally {
                    Menu.jpbBarraProgresso.setIndeterminate(false);
                    Menu.jpbBarraProgresso.setVisible(false);
                }//finally
            }//run
        }.start();
    }//buscar

    /**
     * Método usado para pegar objeto RelogioPonto da linha selecionada
     *
     * @return RelogioPonto
     */
    public RelogioPonto getRelogioPontoSelecionado() {
        if (jtRelogios.getSelectedRow() == -1) {
            return null;
        }

        return relogiosTableModel.getRelogios().get(jtRelogios.getSelectedRow());
    }//getOrdemServicoSelecionada

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIManRelogioPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIManRelogioPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIManRelogioPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIManRelogioPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIManRelogioPonto dialog = new UIManRelogioPonto();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JCheckBox jchAtivo;
    private javax.swing.JLabel jlNome;
    private javax.swing.JTable jtRelogios;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables

}
