package view.epi;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Funcionario;
import services.FuncionarioService;
import services.ServicosFactory;

/**
 *
 * @author guilherme.oliveira
 */
public class UICadAutenticacao extends javax.swing.JDialog {

    public static UIControleEpi uiCE;

    /**
     * Creates new form UICadAutenticacao
     *
     * @param uiCE
     * @param modal
     */
    public UICadAutenticacao(UIControleEpi uiCE) {
        initComponents();
        this.uiCE = uiCE;
    }

    private UICadAutenticacao() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jpfCadSenha = new javax.swing.JPasswordField();
        jlCadSenha = new javax.swing.JLabel();
        jbCadSenha = new javax.swing.JButton();
        jlConfSenha = new javax.swing.JLabel();
        jpfConfSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle Dolphin - Cadastrar Autenticação");
        setModal(true);

        jpfCadSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfCadSenhaKeyPressed(evt);
            }
        });

        jlCadSenha.setText("Senha");

        jbCadSenha.setText("Cadastrar Senha");
        jbCadSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadSenhaActionPerformed(evt);
            }
        });

        jlConfSenha.setText("Confirmar senha");

        jpfConfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfConfSenhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlCadSenha)
                            .addComponent(jpfCadSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jlConfSenha)
                            .addComponent(jpfConfSenha)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jbCadSenha)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlCadSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfCadSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlConfSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jbCadSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Senha", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método usado para cadastrar senha ao pressionar tecla ENTER do teclado
     * quando o foco entiver no campo confSenha
     *
     * @param evt
     */
    private void jpfConfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfConfSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarSenha();
        }
    }//GEN-LAST:event_jpfConfSenhaKeyPressed

    /**
     * Método usado para cadastrar senha do funcionário ao clicar no botão
     * cadastrar senha
     *
     * @param evt
     */
    private void jbCadSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadSenhaActionPerformed
        cadastrarSenha();
    }//GEN-LAST:event_jbCadSenhaActionPerformed

    /**
     * Método usado para cadastrar senha ao pressionar tecla ENTER do teclado
     * quando o foco entiver no campo cadSenha
     *
     * @param evt
     */
    private void jpfCadSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfCadSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarSenha();
        }
    }//GEN-LAST:event_jpfCadSenhaKeyPressed

    /**
     * Método usado para validar senha
     *
     * @return
     */
    public boolean validaSenha() {
        String senha = new String(jpfCadSenha.getPassword());
        String confirmaSenha = new String(jpfConfSenha.getPassword());
        if (senha.length() < 8) {
            limpaCamposSenha();
            JOptionPane.showMessageDialog(null, "A senha deve conter no mínimo 8 digitos!", "Erro ao cadastrar senha!", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!Pattern.matches("[0-9]*", senha)) {
            limpaCamposSenha();
            JOptionPane.showMessageDialog(null, "A senha deve conter apenas números!",
                    "Erro ao cadastrar senha!",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!senha.equalsIgnoreCase(confirmaSenha)) {
            limpaCamposSenha();
            JOptionPane.showMessageDialog(null, "Senhas não são iguais!",
                    "Erro ao cadastrar senha!",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * Método usado para limpar campos
     */
    public void limpaCamposSenha() {
        jpfCadSenha.setText("");
        jpfConfSenha.setText("");
    }

    /**
     * Método usado para cadastrar senha
     */
    public void cadastrarSenha() {
        try {
            FuncionarioService fs = ServicosFactory.getFUNCIONARIOSERVICOS();
            Funcionario f = uiCE.getFuncionarioDaLinhaSelecionada();
            if (validaSenha() == true) {
                String senha = new String(jpfCadSenha.getPassword());
                f.setSenha(Integer.parseInt(senha));
                fs.cadastrarAutenticacao(f);
                JOptionPane.showMessageDialog(null, "Senha cadastrada!");
                limpaCamposSenha();
            }
        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, se.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UICadAutenticacao dialog = new UICadAutenticacao();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCadSenha;
    private javax.swing.JLabel jlCadSenha;
    private javax.swing.JLabel jlConfSenha;
    private javax.swing.JPasswordField jpfCadSenha;
    private javax.swing.JPasswordField jpfConfSenha;
    // End of variables declaration//GEN-END:variables
}
