/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.epi;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.epi.EpiFuncionario;

/**
 *
 * @author ti
 */
public class UICa extends javax.swing.JDialog {

    private final EpiFuncionario epiFuncionario;
    private final UIFuncionarioEPI uiFuncionarioEpi;

    public UICa(UIFuncionarioEPI uiFuncionarioEpi, EpiFuncionario epiFuncionario) {
        this.epiFuncionario = epiFuncionario;
        this.uiFuncionarioEpi = uiFuncionarioEpi;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCCa = new javax.swing.JLabel();
        jtfCCA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setModal(true);

        jlCCa.setText("Digite o CA do EPI");

        jtfCCA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCCAKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCCa)
                    .addComponent(jtfCCA, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCCa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCCAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCCAKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!jtfCCA.getText().isEmpty()) {
                epiFuncionario.setCa(jtfCCA.getText());
                new UIEntregarEPI(uiFuncionarioEpi, epiFuncionario, true).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Campo CA obrigatório!");
            }
        }
    }//GEN-LAST:event_jtfCCAKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCCa;
    private javax.swing.JTextField jtfCCA;
    // End of variables declaration//GEN-END:variables
}
