/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.os;

import dao.DAOFactory;
import dao.os.TipoOsDAO;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.os.TipoOs;

/**
 *
 * @author guilherme.oliveira
 */
public class UICadTipos extends javax.swing.JDialog {

    private UIManTipo telaTipos;
    private TipoOs tipo;
    private TipoOsDAO dao;

    /**
     * Creates new form UICadTipos
     */
    public UICadTipos() {
    }

    public UICadTipos(TipoOs tipo, UIManTipo uiTipo) {
        initComponents();
        this.tipo = tipo;
        this.telaTipos = uiTipo;
        dao = DAOFactory.getTIPOOSDAO();
        preencherCampos();
    }

    /**
     * Método usado para limpar campos
     */
    public void limparCampos() {
        jtfDescricao.setText("");
    }//limparCampos

    /**
     * Método usado para preencher campos
     */
    public void preencherCampos() {

        if (tipo != null) {
            jtfDescricao.setText(tipo.getDescricao());
        }

    }//fecha preencherCampos

    private void setTipo() throws NumberFormatException {
        if (jtfDescricao.getText().isEmpty()) {
            throw new NumberFormatException("Insira a descrição!");
        }

        tipo.setDescricao(jtfDescricao.getText());
    }//setTipo

    private void cadastrar() {
        try {
            
            tipo = new TipoOs();
            
            setTipo();
            
            int id = dao.inserir(tipo);
            
            tipo.setCodTipoOs(id);
            
            telaTipos.getTiposModel().addRow(tipo);
            
            telaTipos.getJcbTipo().addItem(tipo);
            
            JOptionPane.showMessageDialog(this,
                    "Tipo cadastrado!",
                    "",
                    JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
        } catch (NumberFormatException e) {
            tipo = null;
            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Cadastrar tipo", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            tipo = null;
            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Cadastrar tipo", JOptionPane.ERROR_MESSAGE);
        }
    }//inserir
    
    private void editar() {
        try {
            
            setTipo();
            
            dao.alterar(tipo);
            
            JOptionPane.showMessageDialog(this,
                    "Tipo editado!",
                    "",
                    JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Editar tipo", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Editar tipo", JOptionPane.ERROR_MESSAGE);
        }
    }//editar
    
    private void salvar() {
        if (tipo == null) {
            cadastrar();
        } else {
            editar();
        }
    }//salvar
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfDescricao = new javax.swing.JTextField();
        jlDescricao = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Tipo OS/Tarefa");
        setModal(true);

        jtfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDescricaoKeyPressed(evt);
            }
        });

        jlDescricao.setText("Descrição");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 171, Short.MAX_VALUE)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar))
                    .addComponent(jtfDescricao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlDescricao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescricaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar();
        }
    }//GEN-LAST:event_jtfDescricaoKeyPressed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadTipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadTipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadTipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadTipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UICadTipos dialog = new UICadTipos();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JTextField jtfDescricao;
    // End of variables declaration//GEN-END:variables
}
