/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.os;

import dao.DAOFactory;
import dao.os.PessoaTipoDAO;
import dao.os.TipoOsDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.os.Pessoa;
import model.os.PessoaTipo;
import model.os.TipoOs;
import model.os.TipoTableModel;
import view.UICadPessoa;

/**
 *
 * @author guilherme.oliveira
 */
public class UIPermissaoTipo extends javax.swing.JDialog {

    private TipoTableModel tiposModel = new TipoTableModel();
    private UICadPessoa uiCadPessoa;
    private Pessoa pessoa;
    private TipoOs tipo;
    private PessoaTipoDAO ptdao;
    private TipoOsDAO tdao;
    /**
     * Creates new form UIPermissãoTipo
     */
    public UIPermissaoTipo() {
    }

    public UIPermissaoTipo(Pessoa pessoa, UICadPessoa uiCadPessoa) {
        this.uiCadPessoa = uiCadPessoa;
        this.pessoa = pessoa;
        this.ptdao = DAOFactory.getPESSOATIPODAO();
        this.tdao = DAOFactory.getTIPOOSDAO();
        initComponents();
        buscar();
    }

    public void buscar() {
        try {
            String query = "WHERE CODTIPOOS";
            ArrayList<TipoOs> tipos = tdao.filtrar(query);

            for (TipoOs tipoOs : tipos) {
                tiposModel.addRow(tipoOs);
            }//fecha for
            jtTipos.setModel(tiposModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Erro ao buscar tipos da OS/Tarefa", JOptionPane.ERROR_MESSAGE);
        }
    }//filtrar

    public TipoOs getTipoSelecionado() {
        if (jtTipos.getSelectedRow() == -1) {
            return null;
        }
        return tiposModel.getTipoOs().get(jtTipos.getSelectedRow());
    }//fecha getTipoSelecionado

    private void adicionar() {
        try {
            
            PessoaTipo pessoaTipo = new PessoaTipo();

            tipo = getTipoSelecionado();

            if (tipo != null) {

                pessoaTipo.setPessoa(pessoa);
                pessoaTipo.setTipo(tipo);

                ptdao.cadastrar(pessoaTipo);

                uiCadPessoa.atualizarTblPessoasTipos();
                JOptionPane.showMessageDialog(this, "Tipo permitido!");

            } else {
                JOptionPane.showMessageDialog(
                        this, 
                        "Selecione o tipo que deseja permissão!",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE
                );
            }//else

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this, 
                    e.getMessage(),
                    "Erro ao adicionar tipo! ",
                    JOptionPane.ERROR_MESSAGE
            );
        }//catch
    }//adicionar

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtTipos = new javax.swing.JTable();
        jbAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Permissão de tipo");
        setModal(true);
        setResizable(false);

        jtTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTipos);

        jbAdicionar.setText("Adicionar");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAdicionar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        adicionar();
    }//GEN-LAST:event_jbAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPermissaoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPermissaoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPermissaoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPermissaoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIPermissaoTipo dialog = new UIPermissaoTipo();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JTable jtTipos;
    // End of variables declaration//GEN-END:variables
}
